### ISSUE TITLE
Allow for input containing Latin characters instead of the Turkish ones

### ISSUE THREAD

**Issue by anikristo** [cagdass/les-honorables#3]
Allow the user to enter 'c', for example, instead of 'ç', or 's' instead of 'ş'. Ain't nobody got time for Turkish characters.

**Comment by cagdass** [comment]
Thanks Ani, will do that when I can.

**Comment by cagdass** [comment]
Actually, Ani-doll, why don't you be a cutie and implement this for me and send a pull request. GO OPEN SOURCE WOOO!
